PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE4MzgzODgzLCJ1c2VySWQiOjJ9.SqUDIND6LZ64i8hfgD2pRGS2fKxol-LntvyInsiPYEo

{
    "name": "Second Test",
    "description": "A 2º test event",
    "location": "A 2º test location",
    "dateTime": "2026-01-01T15:30:00.000Z"
}